### ISSUE TITLE
Identifying the metadata TABLE element

### ISSUE THREAD

**Issue by mbtaylor** [ivoa/voparquet#3]
The VOParquet convention has to prescribe where in the attached VOTable document to find the `TABLE` element that describes the parquet data, given that there could be multiple `TABLE`s in the VOTable document.  @gpdf's original suggestion was to mark it with a special DATA element
```
<DATA><PARQUET type="Parquet-local-XML"/></DATA>
```
In the initial draft, I have proposed a different solution: it's the unique `TABLE` child of the only `RESOURCE` that is marked with the `type="results"` attribute.  I prefer this because it does not require use of a schema-illegal `PARQUET` element.  It also follows the spirit of DALI, as noted in the text.

Another (simpler?) possibility would be just to say it's the only/first `TABLE` element with no `DATA` child.

Opinions on this can be added in this issue.

**Comment by bsipocz** [comment]
I have already [droped the data element approach in the astropy implementation](https://github.com/astropy/astropy/pull/16375/commits/76e365b67566f7d92ed5537432f2d4c6db056d8b) as per your PR review suggestion and consecutive comments, but looking at it again, the example file has not been updated so there are some cleanup work to be done no matter what the decision is here.

**Comment by mbtaylor** [comment]
On reflection, instead of the business with locating this TABLE element in a particular RESOURCE, I think it would be better just to say that the metadata table element is the first (and likely only) TABLE that has no DATA child.  This is easier to define, easier to code, and harder to get wrong.  It could be a problem if somebody wants to put other DATA-less TABLE elements in the embedded VOTable document as well, but (a) I can't think why they'd want to and (b) it would still be OK as long as they don't put them before the metadata one.

I will draft a PR with this change in the coming days unless people disagree here.

**Comment by fxpineau** [comment]
I agree with your last comment.
I didn't quite like the DALI based  idea of having to locate the `RESOURCE` marked with `type="results"`. 
I tend to prefer not to add dependencies to other standards if not necessary.
In DAL `"result"` makes sense since we get a result by accessing a service.
Here, we annotate a file that can be accessed directly.

Do you expect cases with other `TABLEs` in the VOTable, possibly before the `DATA`-less `TABLE`?
Or could we simplify further locating the first `TABLE` (it **must be** DATA-less)?

What is your approach in FITS-plus?

**Comment by mbtaylor** [comment]
In FITS-plus I always write a single DATA-less TABLE in a single RESOURCE; I've never felt the need to add more TABLE elements to the VOTable document.  The need to write additional TABLEs in the VOTable metadata document hadn't occurred to me, but @gpdf said that he wanted to allow for this possibility.

**Comment by mbtaylor** [comment]
... actually that's not quite true.  A FITS-plus file contains one VOTable in the PHDU but may contain multiple BINTABLEs in extension HDUs.  The VOTable contains one DATA-less TABLE element for each of the BINTABLEs that it annotates, in order, so it may have multiple TABLEs.  But each TABLE maps to a FITS table that needs annotation, there are no non-BINTABLE-annotating tables in there.

**Comment by mbtaylor** [comment]
I like @fxpineau's idea of requiring the DATA-less TABLE to be the first TABLE in the document - why not, it's very simple and it provides an unambiguous rule for finding it. I've written PR #4 to make this change.  Please review if you have an opinion.

**Comment by mbtaylor** [comment]
#4 is merged, so I close this issue.  But it can be reopened if people have further thoughts on the topic.
